classificationQuery = """SELECT
    COUNT(*) AS CNT,
    SUM(b.tot_pages) AS pages,
    SUM(b.tot_pages) / TIMESTAMPDIFF(MINUTE,
        NOW() - INTERVAL 24 HOUR,
        NOW()) AS PagePerMin
FROM
    ICEe.WRKFLW_DTL a
        JOIN
    ICEe.INGS_BLOB_DTL b ON a.BLOB_DTL_ID = b.BLOB_DTL_ID
WHERE
    a.CRE_DTTM >= NOW() - INTERVAL 24 HOUR
        AND a.CRE_DTTM <= NOW()
        AND a.WRKFLW_STEP_TYPE_ID = 5
        AND a.WRKFLW_STS_TYPE_ID = 2
        AND (a.QUEUE_TYPE_ID > 1 AND a.QUEUE_TYPE_ID < 7
        OR (a.QUEUE_TYPE_ID > 37))
GROUP BY a.WRKFLW_STEP_TYPE_ID , a.WRKFLW_STS_TYPE_ID;"""

extractionQuery = """SELECT COUNT(TOT_DOCS) AS DOCS, SUM(PAGE_COUNTS) AS PAGES FROM (SELECT distinct(W.BLOB_DTL_ID) AS TOT_DOCS, count(*) AS PAGE_COUNTS
 FROM ICEe.EDA_EXTRCTN_CLUSTER_DTL W
 JOIN JSON_TABLE(JSON_EXTRACT(W.CLUSTER_JSON,"$.ExtractedDocumentDetails"),'$[*]' COLUMNS (PageSequence varchar(50) path '$')) PG
 WHERE W.CRE_DTTM >= NOW() - INTERVAL 24 HOUR AND W.HITL_STATUS = "HITL-SKIPPED" AND (W.QUEUE_TYPE_ID > 1 AND W.QUEUE_TYPE_ID < 7
OR (W.QUEUE_TYPE_ID > 37))
GROUP BY W.BLOB_DTL_ID) EXT;"""

ingestionBlobs = '''SELECT Batch_ID,count(1) from ICE_Ingestion.ICEIngestion where Status is NULL group by Batch_ID;'''

bbExtractionSplitCountQuery = '''Select DOC_TYPE,count(1) as COUNT from (select W.DOC_TYPE
from EDA_EXTRCTN_WRKFLW_DTL W
where
W.CURR_IND = 1 AND 
((W.WRKFLW_STEP_TYPE_ID = 11 AND W.WRKFLW_STS_TYPE_ID = 2) OR 
(W.WRKFLW_STEP_TYPE_ID = 15 AND W.WRKFLW_STS_TYPE_ID = 7))
AND
(W.QUEUE_TYPE_ID > 1 AND W.QUEUE_TYPE_ID < 7 OR (W.QUEUE_TYPE_ID > 37)) AND
W.CRE_DTTM >= NOW() - INTERVAL 24 HOUR)B group by DOC_TYPE;'''