flowIngestionStatus = """Select WRKFLW_STEP,WRKFLW_STS,count(1) from (select I.ICE_ID,I.TOT_PAGES, STEP.LKP_CD_DESC as WRKFLW_STEP, STS.LKP_CD_DESC as WRKFLW_STS,
I.ERR_DESC, I.CRE_DTTM
from ICE_Ingestion.INGS_ASYNC I
join (select LKP_CD,LKP_CD_DESC from ICE_Ingestion.VW_LKP_MAST_VAL where LKP_MAST_NM = 'WRKFLW_STEP_TYPE') STEP
on
CASE
WHEN I.WRKFLW_STEP_TYPE_ID is null THEN 17
ELSE I.WRKFLW_STEP_TYPE_ID
END = cast(STEP.LKP_CD as UNSIGNED INTEGER)
join
(select LKP_CD,LKP_CD_DESC from ICE_Ingestion.VW_LKP_MAST_VAL where LKP_MAST_NM = 'WRKFLW_STS_TYPE') STS
on
CASE
WHEN I.WRKFLW_STS_TYPE_ID is null THEN 8
ELSE I.WRKFLW_STS_TYPE_ID
END = cast(STS.LKP_CD as UNSIGNED INTEGER)
where
I.QUEUE_TYPE_ID > 6 AND I.QUEUE_TYPE_ID < 35 and
I.CRE_DTTM >= NOW() - INTERVAL 24 HOUR and
    (STEP.LKP_CD_DESC= "Source Document Delivery" or STEP.LKP_CD_DESC= "Loan Validation" or STEP.LKP_CD_DESC= "File Validation") 
    and (STS.LKP_CD_DESC ="Completed" or STS.LKP_CD_DESC="Failed")) B group by WRKFLW_STEP,WRKFLW_STS order by WRKFLW_STEP;
    """


flowCompleted = """Select WRKFLW_STEP,WRKFLW_STS,count(1) from (select  STEP.LKP_CD_DESC as WRKFLW_STEP, STS.LKP_CD_DESC as WRKFLW_STS
from WRKFLW_DTL W
left join INGS_BLOB_DTL I on W.BLOB_DTL_ID = I.BLOB_DTL_ID
left join (select LKP_CD,LKP_CD_DESC from ICEe.VW_LKP_MAST_VAL where LKP_MAST_NM = 'WRKFLW_STEP_TYPE') STEP on W.WRKFLW_STEP_TYPE_ID = cast(STEP.LKP_CD as UNSIGNED INTEGER)
left join (select LKP_CD,LKP_CD_DESC from ICEe.VW_LKP_MAST_VAL where LKP_MAST_NM = 'WRKFLW_STS_TYPE') STS on W.WRKFLW_STS_TYPE_ID = cast(STS.LKP_CD as UNSIGNED INTEGER)
where
W.CRE_DTTM >= NOW() - INTERVAL 24 HOUR
and
W.WRKFLW_STEP_TYPE_ID = 5 AND W.WRKFLW_STS_TYPE_ID =2 AND
W.CURR_IND = '1' and
I.QUEUE_TYPE_ID > 6 AND I.QUEUE_TYPE_ID < 35
) B group by WRKFLW_STEP,WRKFLW_STS;
"""

flowDocs = """
SELECT I.INGS_SELR_DESC as SELLER, CASE
WHEN (FILE_TYPE LIKE 'application/pdf') THEN 'PDFs'
WHEN (FILE_TYPE LIKE 'application/tiff') THEN 'TIFFs'
WHEN (FILE_TYPE LIKE 'application/zip') THEN 'ZIPs'
ELSE FILE_TYPE
END AS FILE_TYPE,
COUNT(*) AS TotalCount from ICE_Ingestion.STG_INGS_RQST SIR
   JOIN ICE_Ingestion.INGS_SELR_TYPE I on JSON_EXTRACT(SIR.metadata, "$.ingestionVendorTypeId") = I.INGS_SELR_TYPE_ID
   where SIR.QUEUE_TYPE_ID > 6 AND SIR.QUEUE_TYPE_ID < 35 and
SIR.CRE_DTTM BETWEEN(NOW() - INTERVAL 24 HOUR) AND NOW()
   GROUP BY SELLER,FILE_TYPE;
"""


flowExtractionDocCount = '''
Select DOC_TYPE,count(1) as COUNT from (select W.DOC_TYPE
from EDA_EXTRCTN_WRKFLW_DTL W
where
W.CURR_IND = 1 AND 
W.WRKFLW_STEP_TYPE_ID = 5 AND
W.WRKFLW_STS_TYPE_ID = 2 AND
W.QUEUE_TYPE_ID > 6 AND W.QUEUE_TYPE_ID < 35 AND 
W.CRE_DTTM >= NOW() - INTERVAL 24 HOUR)B group by DOC_TYPE;
'''
