magNOTE = """select WRKFLW_STEP,WRKFLW_STS,count(1) from (select W.BLOB_DTL_ID, W.EXTRCTN_WRKFLW_DTL_ID,I.ICE_ID,I.TOT_PAGES, WRKFLW_STEP_TYPE_ID as WRKFLW_STEP, WRKFLW_STS_TYPE_ID as WRKFLW_STS,
    W.ERR_DESC, W.CRE_DTTM,W.CURR_IND, NM.RETRY_FLAG
    from ICEe.NOTE_EXTRCTN_WRKFLW_DTL W
    left join ICEe.INGS_BLOB_DTL I on W.BLOB_DTL_ID = I.BLOB_DTL_ID
    left join NOTE_EXTRCTN_MAINMGR NM ON NM.BLOB_DTL_ID = I.BLOB_DTL_ID
    where CURR_IND = '1'
    and  W.CRE_DTTM >= NOW() - INTERVAL 24 HOUR
    -- and W.CRE_DTTM >=NOW() - INTERVAL 74 HOUR
    --  AND SRC_DESC = 'FLOW'
    AND  WRKFLW_STEP_TYPE_ID = 13 and WRKFLW_STS_TYPE_ID = 2) a group by WRKFLW_STEP,WRKFLW_STS;"""

magMortgage = """select WRKFLW_STEP,WRKFLW_STS,count(1) from (select W.BLOB_DTL_ID, W.EXTRCTN_WRKFLW_DTL_ID,I.ICE_ID,I.TOT_PAGES, WRKFLW_STEP_TYPE_ID as WRKFLW_STEP, WRKFLW_STS_TYPE_ID as WRKFLW_STS,
    W.ERR_DESC, W.CRE_DTTM,W.CURR_IND, NM.RETRY_FLAG
    from ICEe.MORTGAGE_EXTRCTN_WRKFLW_DTL W
    left join ICEe.INGS_BLOB_DTL I on W.BLOB_DTL_ID = I.BLOB_DTL_ID
    left join NOTE_EXTRCTN_MAINMGR NM ON NM.BLOB_DTL_ID = I.BLOB_DTL_ID
    where CURR_IND = '1'
    and  W.CRE_DTTM >= NOW() - INTERVAL 24 HOUR
    -- and W.CRE_DTTM >=NOW() - INTERVAL 74 HOUR
    --  AND SRC_DESC = 'FLOW'
    AND  WRKFLW_STEP_TYPE_ID = 13 and WRKFLW_STS_TYPE_ID = 2) a group by WRKFLW_STEP,WRKFLW_STS;"""

magAppraisal = """select WRKFLW_STEP,WRKFLW_STS,count(1) from (select W.BLOB_DTL_ID, W.EXTRCTN_WRKFLW_DTL_ID,I.ICE_ID,I.TOT_PAGES, WRKFLW_STEP_TYPE_ID as WRKFLW_STEP, WRKFLW_STS_TYPE_ID as WRKFLW_STS,
    W.ERR_DESC, W.CRE_DTTM,W.CURR_IND, NM.RETRY_FLAG
    from ICEe.APPRAISAL_EXTRCTN_WRKFLW_DTL W
    left join ICEe.INGS_BLOB_DTL I on W.BLOB_DTL_ID = I.BLOB_DTL_ID
    left join NOTE_EXTRCTN_MAINMGR NM ON NM.BLOB_DTL_ID = I.BLOB_DTL_ID
    where CURR_IND = '1'
    and  W.CRE_DTTM >= NOW() - INTERVAL 24 HOUR
    -- and W.CRE_DTTM >=NOW() - INTERVAL 74 HOUR
    --  AND SRC_DESC = 'FLOW'
    AND  WRKFLW_STEP_TYPE_ID = 13 and WRKFLW_STS_TYPE_ID = 2) a group by WRKFLW_STEP,WRKFLW_STS;"""

mag1003 = """select WRKFLW_STEP,WRKFLW_STS,count(1) from (select W.BLOB_DTL_ID, W.EXTRCTN_WRKFLW_DTL_ID,I.ICE_ID,I.TOT_PAGES, WRKFLW_STEP_TYPE_ID as WRKFLW_STEP, WRKFLW_STS_TYPE_ID as WRKFLW_STS,
    W.ERR_DESC, W.CRE_DTTM,W.CURR_IND, NM.RETRY_FLAG
    from 1003_EXTRCTN_WRKFLW_DTL W
    left join ICEe.INGS_BLOB_DTL I on W.BLOB_DTL_ID = I.BLOB_DTL_ID
    left join NOTE_EXTRCTN_MAINMGR NM ON NM.BLOB_DTL_ID = I.BLOB_DTL_ID
    where CURR_IND = '1'
    and  W.CRE_DTTM >= NOW() - INTERVAL 24 HOUR
    -- and W.CRE_DTTM >=NOW() - INTERVAL 74 HOUR
    --  AND SRC_DESC = 'FLOW'
    AND  WRKFLW_STEP_TYPE_ID = 13 and WRKFLW_STS_TYPE_ID = 2) a group by WRKFLW_STEP,WRKFLW_STS;"""

magW9 = """select WRKFLW_STEP,WRKFLW_STS,count(1) from (select W.BLOB_DTL_ID, W.EXTRCTN_WRKFLW_DTL_ID,I.ICE_ID,I.TOT_PAGES, WRKFLW_STEP_TYPE_ID as WRKFLW_STEP, WRKFLW_STS_TYPE_ID as WRKFLW_STS,
    W.ERR_DESC, W.CRE_DTTM,W.CURR_IND, NM.RETRY_FLAG
    from ICEe.W9_EXTRCTN_WRKFLW_DTL W
    left join ICEe.INGS_BLOB_DTL I on W.BLOB_DTL_ID = I.BLOB_DTL_ID
    left join NOTE_EXTRCTN_MAINMGR NM ON NM.BLOB_DTL_ID = I.BLOB_DTL_ID
    where CURR_IND = '1'
    and  W.CRE_DTTM >= NOW() - INTERVAL 24 HOUR
    -- and W.CRE_DTTM >=NOW() - INTERVAL 74 HOUR
    --  AND SRC_DESC = 'FLOW'
    AND  WRKFLW_STEP_TYPE_ID = 13 and WRKFLW_STS_TYPE_ID = 2) a group by WRKFLW_STEP,WRKFLW_STS;"""

magSSN = """select WRKFLW_STEP,WRKFLW_STS,count(1) from (select W.BLOB_DTL_ID, W.EXTRCTN_WRKFLW_DTL_ID,I.ICE_ID,I.TOT_PAGES, WRKFLW_STEP_TYPE_ID as WRKFLW_STEP, WRKFLW_STS_TYPE_ID as WRKFLW_STS,
W.ERR_DESC, W.CRE_DTTM,W.CURR_IND, NM.RETRY_FLAG
from ICEe.SSN_EXTRCTN_WRKFLW_DTL W
left join ICEe.INGS_BLOB_DTL I on W.BLOB_DTL_ID = I.BLOB_DTL_ID
left join NOTE_EXTRCTN_MAINMGR NM ON NM.BLOB_DTL_ID = I.BLOB_DTL_ID
where CURR_IND = '1'
and  W.CRE_DTTM >= NOW() - INTERVAL 24 HOUR
-- and W.CRE_DTTM >=NOW() - INTERVAL 74 HOUR
--  AND SRC_DESC = 'FLOW'
AND  WRKFLW_STEP_TYPE_ID = 13 and WRKFLW_STS_TYPE_ID = 2) a group by WRKFLW_STEP,WRKFLW_STS;"""

magCD = """select WRKFLW_STEP,WRKFLW_STS,count(1) from (select W.BLOB_DTL_ID, W.EXTRCTN_WRKFLW_DTL_ID,I.ICE_ID,I.TOT_PAGES, WRKFLW_STEP_TYPE_ID as WRKFLW_STEP, WRKFLW_STS_TYPE_ID as WRKFLW_STS,
    W.ERR_DESC, W.CRE_DTTM,W.CURR_IND, NM.RETRY_FLAG
    from ICEe.CD_EXTRCTN_WRKFLW_DTL W
    left join ICEe.INGS_BLOB_DTL I on W.BLOB_DTL_ID = I.BLOB_DTL_ID
    left join NOTE_EXTRCTN_MAINMGR NM ON NM.BLOB_DTL_ID = I.BLOB_DTL_ID
    where CURR_IND = '1'
    and  W.CRE_DTTM >= NOW() - INTERVAL 24 HOUR
    -- and W.CRE_DTTM >=NOW() - INTERVAL 74 HOUR
    --  AND SRC_DESC = 'FLOW'
    AND  WRKFLW_STEP_TYPE_ID = 13 and WRKFLW_STS_TYPE_ID = 2) a group by WRKFLW_STEP,WRKFLW_STS;"""
